<?php 
  /** @var \Magento\Framework\Escaper $escaper */
  /** @var \Magento\Framework\View\Element\Template $block */
  /** @var \Faslet\Connect\ViewModel\ProductWidget $viewModel */

  $viewModel = $block->getViewModel(); 
?>

<?php if ($widgetData = $viewModel->getWidgetData()): ?>
    <?= /* @noEscape */ "<script>console.log(JSON.parse('" . json_encode($widgetData) . "'));</script>"; ?>

    <div class="faslet-widget-box">
        <faslet-app
            shop-id="<?= $escaper->escapeHtmlAttr($widgetData['shop']['id'] ?? ''); ?>"
            brand="<?= $escaper->escapeHtmlAttr($widgetData['product']['brand'] ?? ''); ?>"
            product-identifier="<?= $escaper->escapeHtmlAttr($widgetData['product']['id'] ?? ''); ?>"
            product-name="<?= $escaper->escapeHtmlAttr($widgetData['product']['name'] ?? ''); ?>"
            product-img="<?= $escaper->escapeHtmlAttr($widgetData['product']['image'] ?? ''); ?>"
            platform="Magento 2"
        />
    </div>

    <script>
        (() => {
            const productData = {
                size: '',
                color: '',
            }

            window._faslet = {
                id: "<?= $escaper->escapeJs($widgetData['product']['id'] ?? ''); ?>",
                shopUrl: "<?= $escaper->escapeUrl($widgetData['shop']['url'] ?? ''); ?>",
                sku: "<?= $escaper->escapeJs($widgetData['product']['sku'] ?? ''); ?>",
                variants: <?= /* @noEscape */ json_encode($widgetData['product']['variants'] ?? []); ?>,

                addToCart(_) {
                    const optionSize = document.querySelector(`[aria-label="${productData.size}"]`);
                    const optionColor = document.querySelector(`[aria-label="${productData.color}"]`);
                    const qty = document.querySelector('input[name="qty"]');
                    const addToCart = document.querySelector('#product-addtocart-button');

                    optionSize.click();
                    optionColor.click();
                    qty.value = 1;
                    addToCart.click();
                },

                onResult(result, _) {
                    productData.size = result.label;
                },

                onColorSelected(colorId) {
                    productData.color = colorId;
                },
            }
        })();
    </script>
<?php endif; ?>
